### ISSUE TITLE
Crash serverside with new 0.1.2-20 version

### ISSUE THREAD

**Issue by TheZog** [tterrag1098/WAILAPlugins#53]
Let me know if I can provide any other details. It works fine on one of my worlds (exact same mods installed), but not on this particular server.

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 9/1/15 2:28 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
	at tterrag.wailaplugins.plugins.Plugins.preInit(Plugins.java:109)
	at tterrag.wailaplugins.WailaPlugins.preInit(WailaPlugins.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more


A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-504.3.3.el6.x86_64
	Java Version: 1.7.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4526971640 bytes (4317 MB) / 5211684864 bytes (4970 MB) up to 5211684864 bytes (4970 MB)
	JVM Flags: 5 total; -Xmx5120M -Xms5120M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (custom.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (custom.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	bdlib{1.9.1.97} [BD Lib] (bdlib-1.9.1.97-mc1.7.10.jar) 
	UCH	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.6][MC1.7.10].jar) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
	UCH	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCH	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCH	BuildCraft|Core{7.0.21} [BuildCraft] (buildcraft-7.0.21.jar) 
	UCH	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCH	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCH	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCH	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCH	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCH	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCH	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCH	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCH	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCH	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCH	Botania{r1.7-218} [Botania] (Botania r1.7-218.jar) 
	UCH	BuildCraft|Silicon{7.0.21} [BC Silicon] (buildcraft-7.0.21.jar) 
	UCH	BuildCraft|Factory{7.0.21} [BC Factory] (buildcraft-7.0.21.jar) 
	UCH	BuildCraft|Builders{7.0.21} [BC Builders] (buildcraft-7.0.21.jar) 
	UCH	BuildCraft|Energy{7.0.21} [BC Energy] (buildcraft-7.0.21.jar) 
	UCH	BuildCraft|Robotics{7.0.21} [BC Robotics] (buildcraft-7.0.21.jar) 
	UCH	BuildCraft|Transport{7.0.21} [BC Transport] (buildcraft-7.0.21.jar) 
	UCH	BuildCraft|Compat{7.0.11} [BuildCraft Compat] (buildcraft-compat-7.0.11.jar) 
	UCH	CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCH	chisel{2.9.0.3} [Chisel] (Chisel-2.9.0.3.jar) 
	UCH	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCH	endercore{1.7.10-0.1.0.20_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.20_beta.jar) 
	UCH	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCH	etfuturum{1.4.2} [Et Futurum] (Et Futurum-1.4.2.jar) 
	UCH	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCH	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCH	MagicBees{1.7.10-2.3.4} [Magic Bees] (magicbees-1.7.10-2.3.4.jar) 
	UCH	gendustry{1.5.2.107} [GenDustry] (gendustry-1.5.2.107-mc1.7.10.jar) 
	UCH	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCH	JourneyMapServer{1.0.5_MC1.7.10} [JourneyMapServer] (JourneyMapServer1.0.5_MC1.7.10.jar) 
	UCH	lom{1.7.10-3.0.3} [LotsOMobs] (lom-1.7.10-3.0.3.jar) 
	UCH	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCH	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCH	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCH	rftools{3.34} [RFTools] (rftools-3.34.jar) 
	UCH	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) 
	UCH	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCH	punt{1.7.10-10.13.0-16.1} [Punt] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UCH	whitehall{1.7.10-10.13.0-16.1} [Whitehall] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UCH	hoy{1.7.10-10.13.0-16.1} [Hoy] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UCH	smallboats{1.7.10-10.13.0-16.1} [SmallBoats (base)] (smallboats-1.7.10-10.13.0-16.1.jar) 
	UCH	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCH	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCH	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCH	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCE	wailaplugins{MC1.7.10-0.1.2-20} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-20.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCH	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.0-102.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar
		* BotaniaAPI (61) from Botania r1.7-218.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|blueprints (1.3) from buildcraft-7.0.21.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.11.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.21.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|robotics (2.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.0.21.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.21.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.0.21.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.0.21.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 DEV - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.0.3.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.0.3.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.0.3.jar
		* CoFHAPI (1.7.10R1.0.1) from buildcraft-compat-7.0.11.jar
		* CoFHAPI|block (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from Railcraft_1.7.10-9.7.0.0.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* gendustryAPI (2.1.0) from gendustry-1.5.2.107-mc1.7.10.jar
		* IC2API (1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* McJtyLib (1.4.0) from mcjtylib-1.4.0.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.7.0.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by tterrag1098** [comment]
Fixed in https://github.com/tterrag1098/WAILAPlugins/commit/cc00c45c11320f0e1853c2a92952eff756d75144
