### ISSUE TITLE
Magical Crops Plugin not loading on MC 1.7.10

### ISSUE THREAD

**Issue by NocturneBlock** [tterrag1098/WAILAPlugins#68]
Using Minecraft 1.7.10, Forge 10.13.4.1614, WAILAPlugins-MC1.7.10-0.2.0-23, and Magical Crops 1.7.10.01.

Getting a forge log entry that the Magical Crops plugin is throwing an error and being ignored. In game, none of the special info is shown, presumably because the plugin never loaded.

I have a lot of other mods, but this seems pretty self-contained. Let me know if you would like me to do an isolation load just in case.

**Comment by tterrag1098** [comment]
The error being thrown would be helpful information.

**Comment by NocturneBlock** [comment]
Actually, that was the error, almost verbatim. Here's the relevant section of the log:

[23:51:50] [Client thread/TRACE] [Waila/Waila]: Sending event FMLPreInitializationEvent to mod Waila
[23:51:50] [Client thread/TRACE] [Waila/Waila]: Sent event FMLPreInitializationEvent to mod Waila
[23:51:50] [Client thread/DEBUG] [FML/]: Bar Step: PreInitialization - Waila took 0.210s
[23:51:50] [Client thread/TRACE] [wailaplugins/wailaplugins]: Sending event FMLPreInitializationEvent to mod wailaplugins
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Beginning plugin registration: 14 candidates found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Attempting to create plugin IFluidHandler.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Successfully created plugin IFluidHandler.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin Steamcraft as its dependencies [Steamcraft] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin Forestry as its dependencies [Forestry] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin RedLogic as its dependencies [RedLogic] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin Pam's Fruit as its dependencies [harvestcraft] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin Railcraft as its dependencies [Railcraft] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin Mekanism as its dependencies [Mekanism] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin Blood Magic as its dependencies [AWWayofTime] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin ResourcefulCrops as its dependencies [ResourcefulCrops] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin ExtraUtilities as its dependencies [ExtraUtilities] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Attempting to create plugin Magical Crops.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Successfully created plugin Magical Crops.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Attempting to create plugin DSU.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Successfully created plugin DSU.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin MFR as its dependencies [MineFactoryReloaded] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Skipping over plugin TE Augments as its dependencies [ThermalExpansion] were not found.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Sorting plugins. Before: [IFluidHandler, Magical Crops, DSU]
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Sorting plugins. After:  [IFluidHandler, Magical Crops, DSU]
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Successfully loaded plugin IFluidHandler.
[23:51:50] [Client thread/FATAL] [WAILA Plugins/wailaplugins]: Plugin magicalcrops threw an error on init. Skipping...

**Comment by tterrag1098** [comment]
Just after that....there should be a stacktrace...that is the important bit.

**Comment by NocturneBlock** [comment]
Next section is:
`[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: com/mark719/magicalcrops/blocks/BlockMagicalCrops
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tterrag.wailaplugins.plugins.PluginMagicalCrops.load(PluginMagicalCrops.java:30)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tterrag.wailaplugins.plugins.PluginRegistrar.preInit(PluginRegistrar.java:146)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at tterrag.wailaplugins.WailaPlugins.preInit(WailaPlugins.java:41)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: com.mark719.magicalcrops.blocks.BlockMagicalCrops
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 40 more
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[23:51:50] [Client thread/INFO] [STDERR/wailaplugins]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 42 more
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Successfully loaded plugin DSU.
[23:51:50] [Client thread/INFO] [WAILA Plugins/wailaplugins]: Completed plugin registration. 3 plugins registered.
[23:51:50] [Client thread/TRACE] [wailaplugins/wailaplugins]: Sent event FMLPreInitializationEvent to mod wailaplugins
[23:51:50] [Client thread/DEBUG] [FML/]: Bar Step: PreInitialization - WAILA Plugins took 0.076s`

**Comment by tterrag1098** [comment]
Yes. Clearly MagicalCrops decided to change everything again for no reason. I'll have to adapt the plugin, eventually.

**Comment by NocturneBlock** [comment]
Okay, sorry to be the messenger on that. Relevant for adapting the plugin, be aware that Mark719 apparently decided to make Magical Crops modular, and there are currently two nominally 1.7.10 versions on Curse: the modular one and the all-in-one that I am using. I believe the modular one will be the active one moving forward, but I haven't managed to get it to work; it crashes my system, so I have just stuck with the AIO version for the moment. Maybe the plugin is happier with the modular version?

[https://mods.curse.com/search?search=Magical+Crops&submit-search=Submit+Query](url)

Also, there is now a "spiritual successor" to Magical Crops for later versions of Minecraft, since the original is no longer being developed (Mark719 is looking for someone to pick it up, so it might not be dead). 

[https://mods.curse.com/mc-mods/minecraft/246640-mystical-agriculture](url)

(Sorry, can't figure out how to get Github to consider those outside links, but they work if you copy and paste them into the address bar.)
